/* RNI28106 — Contactos y clientes v2. Reemplaza la implementación anterior. */
(function(){
'use strict';
if(typeof S==='undefined') return;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=v=>String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const arr=k=>Array.isArray(S[k])?S[k]:[];
const id=()=>typeof uid==='function'?uid():`ct-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const name=c=>c?.clienteNombre||c?.empresa||c?.nombre||'';
function qname(q){return q?.cliente||q?.clienteNombre||q?.nombreCliente||q?.razonSocial||q?.empresa||q?.datosCliente?.nombre||'';}
function pname(p){return p?.cliente||p?.entidad||p?.clienteNombre||p?.nombreCliente||p?.razonSocial||'';}
function project(q){return q?.proyecto||q?.proyectoNombre||q?.nombreProyecto||q?.obra||q?.contrato||'';}
function related(c){const i=norm(c.id);return {quotes:arr('cotizaciones').filter(q=>norm(q.contactoId)===i),payments:arr('pagos').filter(p=>norm(p.contactoId)===i),projects:[...new Set([...(c.proyectos||[]),...arr('cotizaciones').filter(q=>norm(q.contactoId)===i).map(project).filter(Boolean)])]};}
function migrate(){
 S.contactos=arr('contactos');S.clientes=arr('clientes');
 const byName=new Map(S.contactos.map(c=>[norm(name(c)),c]));
 for(const cl of S.clientes){const n=String(cl.nombre||cl.razonSocial||cl.empresa||'').trim();if(!n)continue;let c=cl.contactoId&&S.contactos.find(x=>norm(x.id)===norm(cl.contactoId));if(!c)c=byName.get(norm(n));if(!c){c={id:id(),nombre:cl.personaContacto||n,empresa:cl.empresa||'',cargo:cl.cargo||'',tipoPersona:cl.tipoPersona||'empresa',telefono:cl.telefono||'',whatsapp:cl.whatsapp||'',email:cl.email||cl.correo||'',nit:cl.nit||'',documento:cl.documento||cl.ci||'',ciudad:cl.ciudad||'',direccion:cl.direccion||'',esCliente:true,clienteId:cl.id,clienteNombre:n,proyectos:Array.isArray(cl.proyectos)?cl.proyectos:[],notas:cl.notas||''};S.contactos.push(c);byName.set(norm(n),c);}else{c.esCliente=true;c.clienteId=c.clienteId||cl.id;c.clienteNombre=c.clienteNombre||n;for(const k of ['empresa','cargo','telefono','whatsapp','email','nit','documento','ciudad','direccion','notas'])if(!c[k]&&cl[k])c[k]=cl[k];}}
 for(const q of arr('cotizaciones')){const n=qname(q);if(!n)continue;let c=q.contactoId&&S.contactos.find(x=>norm(x.id)===norm(q.contactoId));if(!c)c=byName.get(norm(n));if(!c){c={id:id(),nombre:n,empresa:q.empresa||q.razonSocial||'',telefono:q.telefono||'',whatsapp:q.whatsapp||'',email:q.email||q.correo||'',nit:q.nit||'',documento:q.ci||q.documento||'',ciudad:q.ciudad||'',direccion:q.direccion||'',tipoPersona:'empresa',esCliente:true,clienteId:id(),clienteNombre:n,proyectos:[],notas:''};S.contactos.push(c);byName.set(norm(n),c);}c.esCliente=true;c.clienteId=c.clienteId||id();c.clienteNombre=c.clienteNombre||n;if(project(q)&&!(c.proyectos||[]).includes(project(q)))c.proyectos=[...(c.proyectos||[]),project(q)];q.contactoId=c.id;}
 for(const p of arr('pagos')){const n=pname(p);if(!n)continue;let c=p.contactoId&&S.contactos.find(x=>norm(x.id)===norm(p.contactoId));if(!c)c=byName.get(norm(n));if(!c){c={id:id(),nombre:n,empresa:n,telefono:p.telefono||'',whatsapp:p.whatsapp||'',email:p.email||p.correo||'',nit:p.nit||'',documento:p.documento||'',ciudad:p.ciudad||'',direccion:p.direccion||'',tipoPersona:'empresa',esCliente:true,clienteId:id(),clienteNombre:n,proyectos:[],notas:''};S.contactos.push(c);byName.set(norm(n),c);}c.esCliente=true;c.clienteId=c.clienteId||id();c.clienteNombre=c.clienteNombre||n;p.contactoId=c.id;}
}
function syncClients(){
 const out=[];for(const c of arr('contactos'))if(c.esCliente){const rel=related(c);const cid=c.clienteId||id();c.clienteId=cid;out.push({id:cid,nombre:name(c),contactoId:c.id,contacto:c.nombre||'',personaContacto:c.nombre||'',empresa:c.empresa||'',cargo:c.cargo||'',telefono:c.telefono||'',whatsapp:c.whatsapp||'',email:c.email||'',nit:c.nit||'',documento:c.documento||'',ciudad:c.ciudad||'',direccion:c.direccion||'',proyectos:rel.projects,notas:c.notas||'',tipoPersona:c.tipoPersona||'persona'});}S.clientes=out;}
async function persist(){if(!S.user?.uid){toast?.('⚠️ Debes iniciar sesión para guardar.');return false;}syncClients();try{await saveContactos(S.user.uid);await saveClientes(S.user.uid);await saveCotizaciones(S.user.uid);await savePagos(S.user.uid);return true;}catch(e){console.error('Contactos v2:',e);toast?.('❌ No se pudo guardar en Firebase.');return false;}}
function modal(id){const old=id&&arr('contactos').find(c=>norm(c.id)===norm(id));const c=old||{id:id(),nombre:'',empresa:'',cargo:'',tipoPersona:'persona',telefono:'',whatsapp:'',email:'',nit:'',documento:'',ciudad:'',direccion:'',esCliente:false,proyectos:[],notas:''};const ov=document.createElement('div');ov.className='overlay';ov.dataset.rniContactV2='1';ov.innerHTML=`<div class="modal" style="max-width:900px;width:96%;max-height:92vh;overflow:auto"><div class="modal-h"><h3>${old?'Editar contacto':'Nuevo contacto'}</h3><button type="button" class="close" data-v2="close">×</button></div><div class="modal-body"><div class="row2"><div class="field"><label>Nombre / Persona *</label><input data-f="nombre" value="${esc(c.nombre)}"></div><div class="field"><label>Empresa / Institución</label><input data-f="empresa" value="${esc(c.empresa)}"></div></div><div class="row3"><div class="field"><label>Cargo / función</label><input data-f="cargo" value="${esc(c.cargo)}"></div><div class="field"><label>Tipo</label><select data-f="tipoPersona"><option value="persona" ${c.tipoPersona==='persona'?'selected':''}>Persona natural</option><option value="empresa" ${c.tipoPersona==='empresa'?'selected':''}>Empresa / institución</option></select></div><div class="field"><label>Es cliente</label><select data-f="esCliente"><option value="0" ${!c.esCliente?'selected':''}>No</option><option value="1" ${c.esCliente?'selected':''}>Sí</option></select></div></div><div class="row3"><div class="field"><label>Teléfono</label><input data-f="telefono" value="${esc(c.telefono)}"></div><div class="field"><label>WhatsApp</label><input data-f="whatsapp" value="${esc(c.whatsapp)}"></div><div class="field"><label>Correo</label><input data-f="email" type="email" value="${esc(c.email||c.correo)}"></div></div><div class="row3"><div class="field"><label>NIT</label><input data-f="nit" value="${esc(c.nit)}"></div><div class="field"><label>CI / Documento</label><input data-f="documento" value="${esc(c.documento||c.ci)}"></div><div class="field"><label>Ciudad</label><input data-f="ciudad" value="${esc(c.ciudad)}"></div></div><div class="field"><label>Dirección</label><input data-f="direccion" value="${esc(c.direccion)}"></div><div class="field"><label>Proyectos asociados</label><textarea data-f="proyectos" rows="5">${esc((c.proyectos||[]).join('\n'))}</textarea></div><div class="field"><label>Notas / información adicional</label><textarea data-f="notas" rows="4">${esc(c.notas||'')}</textarea></div></div><div class="modal-foot"><button type="button" class="btn btn-ghost" data-v2="cancel">Cancelar</button><button type="button" class="btn btn-primary" data-v2="save">💾 Guardar</button></div></div>`;ov.querySelector('[data-v2="save"]').dataset.id=old?old.id:'';document.body.appendChild(ov);ov.addEventListener('mousedown',e=>{if(e.target===ov)ov.remove();});}
function view(){migrate();const list=arr('contactos');const clients=list.filter(c=>c.esCliente);const query=norm(document.querySelector('#rni-v2-search')?.value);const filtered=query?list.filter(c=>norm([c.nombre,c.empresa,c.email,c.telefono,c.ciudad,c.cargo,c.clienteNombre].join(' ')).includes(query)):list;document.getElementById('main').innerHTML=`<div class="page-head"><div><div class="eyebrow">RED PROFESIONAL</div><h1>Contactos y clientes</h1><p>Directorio único con información profesional, clientes, proyectos y relaciones financieras.</p></div><div class="page-actions"><button class="btn btn-primary" data-v2="new">＋ Nuevo contacto</button></div></div><div class="kpi-grid"><div class="kpi"><div class="label">Contactos</div><div class="val">${list.length}</div><div class="sub">Directorio total</div></div><div class="kpi accent"><div class="label">Clientes</div><div class="val">${clients.length}</div><div class="sub">Con relación comercial</div></div><div class="kpi success"><div class="label">Con teléfono</div><div class="val">${list.filter(c=>c.telefono||c.whatsapp).length}</div><div class="sub">Contacto directo</div></div><div class="kpi"><div class="label">Con correo</div><div class="val">${list.filter(c=>c.email).length}</div><div class="sub">Comunicación digital</div></div></div><div class="panel"><div class="panel-h"><h3>Directorio</h3><input id="rni-v2-search" class="search-input" placeholder="Buscar nombre, empresa, correo..." value="${esc(document.querySelector('#rni-v2-search')?.value||'')}"></div><div class="table-wrap"><table><thead><tr><th>Contacto</th><th>Empresa / cargo</th><th>Teléfono</th><th>Correo</th><th>Cliente</th><th>Relaciones</th><th></th></tr></thead><tbody>${filtered.map(c=>{const r=related(c);return `<tr><td><b>${esc(c.nombre||c.clienteNombre||c.empresa||'Sin nombre')}</b><div class="muted">${esc(c.ciudad||'')}</div></td><td>${esc(c.empresa||'—')}<div class="muted">${esc(c.cargo||'')}</div></td><td>${esc(c.whatsapp||c.telefono||'—')}</td><td>${esc(c.email||'—')}</td><td>${c.esCliente?'✓ Sí':'—'}</td><td>${r.quotes.length} cot. · ${r.payments.length} pagos · ${r.projects.length} proy.</td><td><div class="rowactions"><button class="iconbtn" data-v2="edit" data-id="${esc(c.id)}">✎</button><button class="iconbtn" data-v2="delete" data-id="${esc(c.id)}">×</button></div></td></tr>`;}).join('')||'<tr><td colspan="7" style="text-align:center;padding:30px">No hay contactos.</td></tr>'}</tbody></table></div></div>`;document.getElementById('rni-v2-search')?.addEventListener('input',view);}
view._rniV2=true;
if(typeof viewContactos==='function') viewContactos=view;
const oldRender=render;render=function(){if(S.view==='clientes')S.view='contactos';oldRender();document.querySelectorAll('[data-nav="clientes"]').forEach(x=>x.remove());document.querySelectorAll('#ios-nav-select option[value="clientes"]').forEach(x=>x.remove());};
document.addEventListener('click',async e=>{const b=e.target.closest('[data-v2]');if(!b)return;const a=b.dataset.v2;if(a==='new'){modal('');return;}if(a==='close'||a==='cancel'){b.closest('[data-rni-contact-v2]')?.remove();return;}if(a==='edit'){modal(b.dataset.id);return;}if(a==='delete'){const c=arr('contactos').find(x=>norm(x.id)===norm(b.dataset.id));if(c&&!confirm(`¿Eliminar ${name(c)}?`))return;S.contactos=S.contactos.filter(x=>norm(x.id)!==norm(b.dataset.id));for(const q of arr('cotizaciones'))if(norm(q.contactoId)===norm(b.dataset.id))delete q.contactoId;for(const p of arr('pagos'))if(norm(p.contactoId)===norm(b.dataset.id))delete p.contactoId;await persist();render();toast?.('Contacto eliminado.');return;}if(a==='save'){const ov=b.closest('[data-rni-contact-v2]');const oid=b.dataset.id;const old=oid&&arr('contactos').find(c=>norm(c.id)===norm(oid));const get=k=>ov.querySelector(`[data-f="${k}"]`)?.value?.trim()||'';const c={...(old||{}),id:old?.id||id(),nombre:get('nombre'),empresa:get('empresa'),cargo:get('cargo'),tipoPersona:get('tipoPersona')||'persona',telefono:get('telefono'),whatsapp:get('whatsapp'),email:get('email'),nit:get('nit'),documento:get('documento'),ciudad:get('ciudad'),direccion:get('direccion'),esCliente:get('esCliente')==='1',proyectos:get('proyectos').split(/\n|;/).map(x=>x.trim()).filter(Boolean),notas:get('notas'),creadoEn:old?.creadoEn||new Date().toISOString(),actualizadoEn:new Date().toISOString()};if(!c.nombre){toast?.('⚠️ El nombre es obligatorio.');return;}if(c.esCliente){c.clienteId=old?.clienteId||id();c.clienteNombre=c.empresa||c.nombre;}else{c.clienteId=null;c.clienteNombre='';}if(old)S.contactos=S.contactos.map(x=>norm(x.id)===norm(old.id)?c:x);else S.contactos.push(c);if(old?.esCliente&&!c.esCliente)S.clientes=arr('clientes').filter(x=>norm(x.id)!==norm(old.clienteId));ov.remove();const ok=await persist();if(ok){render();toast?.('✅ Contacto guardado.');}return;}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('[data-rni-contact-v2]')?.remove();});
})();