/* CONTACTOS + CLIENTES — módulo unificado y autoritativo. */
(function(w){
'use strict';
const N=v=>String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const E=v=>w.esc?w.esc(v??''):String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const A=v=>w.attr?w.attr(v??''):E(v);
const U=()=>w.uid?w.uid():`ct-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const F=(...xs)=>{for(const x of xs){if(x===null||x===undefined)continue;if(typeof x==='object'){const y=F(x.nombre,x.nombreCompleto,x.razonSocial,x.empresa,x.name,x.titular);if(y)return y}else{const s=String(x).trim();if(s)return s}}return ''};
let saving=false, expanded=null, started=false;
function quoteClientName(q){return F(q?.cliente,q?.clienteNombre,q?.nombreCliente,q?.razonSocial,q?.empresa,q?.datosCliente?.nombre,q?.datosCliente?.razonSocial,q?.datosCliente?.empresa)}
function quoteEmail(q){return F(q?.email,q?.correo,q?.cliente?.email,q?.datosCliente?.email)}
function quotePhone(q){return F(q?.telefono,q?.whatsapp,q?.cliente?.telefono,q?.datosCliente?.telefono)}
function quoteProject(q){return F(q?.proyecto,q?.proyectoNombre,q?.nombreProyecto,q?.obra,q?.contrato)}
function paymentClient(p){return F(p?.cliente,p?.entidad,p?.clienteNombre,p?.nombreCliente,p?.razonSocial)}
function contactMatch(name,email,phone){const en=N(email),ph=N(phone),nn=N(name);return (S.contactos||[]).find(c=>(en&&N(c.email||c.correo)===en)||(ph&&N(c.telefono||c.whatsapp)===ph)||(nn&&(N(c.clienteNombre)===nn||N(c.empresa)===nn||N(c.nombre)===nn)))}
function relQuotes(c){const id=N(c?.id),keys=[c?.clienteNombre,c?.empresa,c?.nombre].map(N).filter(Boolean);return (S.cotizaciones||[]).filter(q=>N(q?.contactoId)===id||(keys.length&&keys.includes(N(quoteClientName(q)))))}
function relPayments(c){const id=N(c?.id),keys=[c?.clienteNombre,c?.empresa,c?.nombre].map(N).filter(Boolean);return (S.pagos||[]).filter(p=>N(p?.contactoId)===id||(keys.length&&keys.includes(N(paymentClient(p)))))}
function relProjects(c){const out=Array.isArray(c?.proyectos)?[...c.proyectos]:String(c?.proyectos||'').split(/\n|;/).map(x=>x.trim()).filter(Boolean);relQuotes(c).forEach(q=>{const p=quoteProject(q);if(p)out.push(p)});return [...new Set(out)]}
function migrateStoredClients(){S.contactos=Array.isArray(S.contactos)?S.contactos:[];S.clientes=Array.isArray(S.clientes)?S.clientes:[];for(const cl of S.clientes){const name=F(cl.nombre,cl.razonSocial,cl.cliente,cl.empresa);if(!name)continue;let c=cl.contactoId&&S.contactos.find(x=>N(x.id)===N(cl.contactoId));if(!c)c=contactMatch(name,cl.email||cl.correo,cl.telefono||cl.whatsapp);if(!c){c={id:U(),nombre:F(cl.contacto,cl.personaContacto,name),empresa:F(cl.empresa,name),cargo:cl.cargo||'',telefono:cl.telefono||'',whatsapp:cl.whatsapp||'',email:cl.email||cl.correo||'',nit:cl.nit||'',documento:cl.documento||cl.ci||'',ciudad:cl.ciudad||'',direccion:cl.direccion||'',tipoPersona:cl.tipoPersona||'persona',esCliente:true,clienteId:cl.id,clienteNombre:name,proyectos:Array.isArray(cl.proyectos)?cl.proyectos:[],notas:cl.notas||''};S.contactos.push(c)}else{Object.assign(c,{esCliente:true,clienteId:cl.id,clienteNombre:name,empresa:F(c.empresa,cl.empresa,name),cargo:F(c.cargo,cl.cargo),telefono:F(c.telefono,cl.telefono),whatsapp:F(c.whatsapp,cl.whatsapp),email:F(c.email,c.correo,cl.email,cl.correo),nit:F(c.nit,cl.nit),documento:F(c.documento,c.ci,cl.documento,cl.ci),ciudad:F(c.ciudad,cl.ciudad),direccion:F(c.direccion,cl.direccion),proyectos:relProjects({...c,...cl}),notas:F(c.notas,cl.notas)})}cl.contactoId=c.id}}
function ensureQuoteClients(){let changed=false;S.contactos=Array.isArray(S.contactos)?S.contactos:[];S.cotizaciones=Array.isArray(S.cotizaciones)?S.cotizaciones:[];S.pagos=Array.isArray(S.pagos)?S.pagos:[];for(const q of S.cotizaciones){const name=quoteClientName(q);if(!name)continue;const email=quoteEmail(q),phone=quotePhone(q);let c=contactMatch(name,email,phone);if(!c){c={id:U(),nombre:name,empresa:F(q.empresa,q.razonSocial),cargo:'',telefono:phone,whatsapp:F(q.whatsapp),email:email,nit:F(q.nit,q.NIT),documento:F(q.documento,q.ci),ciudad:F(q.ciudad),direccion:F(q.direccion),tipoPersona:q.tipoPersona||'empresa',esCliente:true,clienteId:U(),clienteNombre:name,proyectos:[],notas:''};S.contactos.push(c);changed=true}else{const before=JSON.stringify([c.esCliente,c.clienteNombre,c.email,c.telefono,c.nit]);Object.assign(c,{esCliente:true,clienteNombre:name,clienteId:c.clienteId||U(),email:F(c.email,email),telefono:F(c.telefono,phone),whatsapp:F(c.whatsapp,q.whatsapp),nit:F(c.nit,q.nit),empresa:F(c.empresa,q.empresa)});if(before!==JSON.stringify([c.esCliente,c.clienteNombre,c.email,c.telefono,c.nit]))changed=true}const p=quoteProject(q);if(p&&!relProjects(c).includes(p)){c.proyectos=[...(c.proyectos||[]),p];changed=true}if(N(q.contactoId)!==N(c.id)){q.contactoId=c.id;changed=true}}
for(const p of S.pagos){const name=paymentClient(p);if(!name)continue;let c=contactMatch(name,F(p.email,p.correo),F(p.telefono,p.whatsapp));if(!c){c={id:U(),nombre:name,empresa:name,cargo:'',telefono:F(p.telefono),whatsapp:F(p.whatsapp),email:F(p.email,p.correo),nit:F(p.nit),documento:F(p.documento),ciudad:F(p.ciudad),direccion:F(p.direccion),tipoPersona:'empresa',esCliente:true,clienteId:U(),clienteNombre:name,proyectos:[],notas:''};S.contactos.push(c);changed=true}else if(!c.esCliente){c.esCliente=true;c.clienteNombre=name;c.clienteId=c.clienteId||U();changed=true}if(N(p.contactoId)!==N(c.id)){p.contactoId=c.id;changed=true}}
return changed}
function syncClients(){S.clientes=Array.isArray(S.clientes)?S.clientes:[];for(const c of (S.contactos||[]).filter(x=>x.esCliente)){let cl=c.clienteId&&S.clientes.find(x=>N(x.id)===N(c.clienteId));if(!cl)cl=S.clientes.find(x=>N(F(x.nombre,x.razonSocial,x.cliente,x.empresa))===N(c.clienteNombre||c.empresa||c.nombre));if(!cl){cl={id:U(),nombre:c.clienteNombre||c.empresa||c.nombre,proyectos:[]};S.clientes.push(cl)}Object.assign(cl,{nombre:c.clienteNombre||c.empresa||c.nombre,contactoId:c.id,contacto:c.nombre,personaContacto:c.nombre,cargo:c.cargo||'',telefono:c.telefono||'',whatsapp:c.whatsapp||'',email:c.email||'',nit:c.nit||'',documento:c.documento||'',ciudad:c.ciudad||'',direccion:c.direccion||'',proyectos:relProjects(c),notas:c.notas||'',tipoPersona:c.tipoPersona||'persona'})}}
async function persist(){if(saving)return;saving=true;try{syncClients();const uid=S.user?.uid;await w.saveContactos?.(uid);await w.saveClientes?.(uid);await w.saveCotizaciones?.(uid);await w.savePagos?.(uid)}catch(e){console.error('Contactos y clientes:',e);w.toast?.('❌ No se pudieron guardar los cambios.')}finally{saving=false}}
function modal(id){const old=id&&(S.contactos||[]).find(c=>N(c.id)===N(id));const c=old?{...old}:{id:U(),nombre:'',empresa:'',cargo:'',telefono:'',whatsapp:'',email:'',nit:'',documento:'',ciudad:'',direccion:'',tipoPersona:'persona',esCliente:false,proyectos:[],notas:''};const ov=document.createElement('div');ov.className='overlay';ov.dataset.contactModal='1';ov.style.zIndex='10080';ov.innerHTML=`<div class="modal" style="max-width:900px;width:calc(100% - 24px);max-height:92vh;overflow:hidden"><div class="modal-h"><h3>${old?'✏️ Editar contacto':'➕ Nuevo contacto'}</h3><button type="button" class="close" data-modal-close>&times;</button></div><div class="modal-body" style="overflow:auto"><div class="row2"><div class="field"><label>Nombre / Persona *</label><input data-f="nombre" value="${A(c.nombre)}"></div><div class="field"><label>Empresa / Institución</label><input data-f="empresa" value="${A(c.empresa)}"></div></div><div class="row3"><div class="field"><label>Cargo / función</label><input data-f="cargo" value="${A(c.cargo)}"></div><div class="field"><label>Tipo</label><select data-f="tipoPersona"><option value="persona" ${c.tipoPersona==='persona'?'selected':''}>Persona natural</option><option value="empresa" ${c.tipoPersona==='empresa'?'selected':''}>Empresa / institución</option></select></div><div class="field"><label>Es cliente</label><select data-f="esCliente"><option value="0" ${!c.esCliente?'selected':''}>No</option><option value="1" ${c.esCliente?'selected':''}>Sí</option></select></div></div><div class="row3"><div class="field"><label>Teléfono</label><input data-f="telefono" value="${A(c.telefono)}"></div><div class="field"><label>WhatsApp</label><input data-f="whatsapp" value="${A(c.whatsapp)}"></div><div class="field"><label>Correo</label><input data-f="email" value="${A(c.email||c.correo)}"></div></div><div class="row3"><div class="field"><label>NIT</label><input data-f="nit" value="${A(c.nit)}"></div><div class="field"><label>CI / Documento</label><input data-f="documento" value="${A(c.documento||c.ci)}"></div><div class="field"><label>Ciudad</label><input data-f="ciudad" value="${A(c.ciudad)}"></div></div><div class="field"><label>Dirección</label><input data-f="direccion" value="${A(c.direccion)}"></div><div class="field"><label>Proyectos asociados</label><textarea data-f="proyectos" rows="5">${E(relProjects(c).join('\n'))}</textarea></div><div class="field"><label>Notas / información adicional</label><textarea data-f="notas" rows="4">${E(c.notas||'')}</textarea></div></div><div class="modal-foot"><button type="button" class="btn btn-ghost" data-modal-close>Cancelar</button><button type="button" class="btn btn-primary" data-contact-save>💾 Guardar</button></div></div>`;document.body.appendChild(ov)}
async function saveModal(ov){const oldId=ov.querySelector('[data-contact-save]')?.dataset.id;const old=oldId&&(S.contactos||[]).find(c=>N(c.id)===N(oldId));const val=k=>ov.querySelector(`[data-f="${k}"]`)?.value?.trim()||'';const name=val('nombre');if(!name){w.toast?.('⚠️ El nombre es obligatorio.');return}const nuevo={...(old||{}),id:old?.id||U(),nombre:name,empresa:val('empresa'),cargo:val('cargo'),tipoPersona:val('tipoPersona')||'persona',esCliente:val('esCliente')==='1',telefono:val('telefono'),whatsapp:val('whatsapp'),email:val('email'),nit:val('nit'),documento:val('documento'),ciudad:val('ciudad'),direccion:val('direccion'),proyectos:[...new Set(val('proyectos').split('\n').map(x=>x.trim()).filter(Boolean))],notas:val('notas'),actualizadoEn:new Date().toISOString()};if(nuevo.esCliente){nuevo.clienteNombre=nuevo.empresa||nuevo.nombre;nuevo.clienteId=old?.clienteId||U()}else{delete nuevo.clienteId;delete nuevo.clienteNombre}if(old)S.contactos=S.contactos.map(c=>N(c.id)===N(old.id)?nuevo:c);else S.contactos.push(nuevo);if(old?.esCliente&&nuevo.esCliente&&N(old.clienteNombre||old.empresa||old.nombre)!==N(nuevo.clienteNombre)){const from=N(old.clienteNombre||old.empresa||old.nombre),to=nuevo.clienteNombre;S.cotizaciones=(S.cotizaciones||[]).map(q=>N(quoteClientName(q))===from?{...q,cliente:to,contactoId:nuevo.id}:q);S.pagos=(S.pagos||[]).map(p=>N(paymentClient(p))===from?{...p,cliente:to,entidad:p.entidad&&N(p.entidad)===from?to:p.entidad,contactoId:nuevo.id}:p)}ov.remove();await persist();w.render?.();w.toast?.('✅ Contacto guardado correctamente.')}
function relationBox(c){const qs=relQuotes(c),ps=relPayments(c),pr=relProjects(c);const key=String(c.id);if(expanded!==key)return `<button type="button" class="btn btn-sm btn-ghost" data-rel="${A(c.id)}">Ver detalle</button>`;return `<div class="relation-detail"><div><b>📁 Proyectos (${pr.length})</b>${pr.length?`<ul>${pr.map(x=>`<li>${E(x)}</li>`).join('')}</ul>`:'<span>Sin proyectos asociados.</span>'}</div><div><b>▤ Cotizaciones (${qs.length})</b>${qs.length?`<ul>${qs.map(q=>`<li><b>${E(quoteProject(q)||'Sin proyecto')}</b> — ${E(q.fecha||q.createdAt||'')} ${q.montoTotal||q.total||q.monto?`· Bs ${E(q.montoTotal||q.total||q.monto)}`:''}</li>`).join('')}</ul>`:'<span>Sin cotizaciones.</span>'}</div><div><b>💰 Pagos (${ps.length})</b>${ps.length?`<ul>${ps.map(p=>`<li>${E(p.concepto||p.descripcion||'Pago')} — ${E(p.fecha||p.createdAt||'')} ${p.montoPagado||p.monto?`· Bs ${E(p.montoPagado||p.monto)}`:''}</li>`).join('')}</ul>`:'<span>Sin pagos registrados.</span>'}</div><button type="button" class="btn btn-sm btn-ghost" data-rel="${A(c.id)}">Ocultar detalle</button></div>`}
function view(){migrateStoredClients();ensureQuoteClients();const rows=S.contactos||[];const q=N(S.contFilters?.nombre),e=N(S.contFilters?.empresa),ca=N(S.contFilters?.cargo);const f=rows.filter(c=>(!q||N(c.nombre).includes(q)||N(c.clienteNombre).includes(q))&&(!e||N(c.empresa||c.clienteNombre).includes(e))&&(!ca||N(c.cargo).includes(ca)));return `<div class="page-head"><div><p class="eyebrow">Red profesional</p><h1>Contactos y clientes</h1><p>Personas, empresas y clientes en una sola ficha.</p></div><div class="page-actions"><button type="button" class="btn btn-primary" data-contact-new>＋ Nuevo contacto</button></div></div><div class="panel"><div class="panel-body"><div class="filter-bar"><label>🔍 Filtros:</label><input data-filter="nombre" placeholder="Nombre..." value="${A(S.contFilters?.nombre||'')}"><input data-filter="empresa" placeholder="Empresa / cliente..." value="${A(S.contFilters?.empresa||'')}"><input data-filter="cargo" placeholder="Cargo..." value="${A(S.contFilters?.cargo||'')}"><button type="button" class="btn btn-sm btn-ghost" data-filter-apply>Aplicar</button><span class="filter-clear" data-filter-clear>Limpiar</span></div>${f.length?`<div class="table-wrap"><table><thead><tr><th>Contacto</th><th>Empresa / Cliente</th><th>Cargo</th><th>Contacto directo</th><th>Relaciones</th><th>Acciones</th></tr></thead><tbody>${f.map(c=>{const qs=relQuotes(c),ps=relPayments(c),pr=relProjects(c);return `<tr><td><b>${E(c.nombre)}</b>${c.esCliente?' <span class="stamp aceptada">CLIENTE</span>':''}</td><td>${E(c.empresa||c.clienteNombre||'—')}</td><td>${E(c.cargo||'—')}</td><td>${E(c.telefono||'—')}<br><span style="color:var(--text-soft)">${E(c.email||'')}</span></td><td><div class="rel-summary"><span>📁 ${pr.length} proyectos</span><span>▤ ${qs.length} cotizaciones</span><span>💰 ${ps.length} pagos</span></div>${relationBox(c)}</td><td><div class="rowactions"><button type="button" class="iconbtn" data-edit-contact="${A(c.id)}" title="Editar">✎</button><button type="button" class="iconbtn" data-delete-contact="${A(c.id)}" title="Eliminar">🗑</button></div></td></tr>${expanded===String(c.id)?`<tr class="relation-row"><td colspan="6">${relationBox(c)}</td></tr>`:''}`}).join('')}</tbody></table></div>`:'<div class="empty"><div>No hay contactos ni clientes registrados.</div><small>Los clientes de cotizaciones y pagos se incorporan automáticamente.</small></div>'}</div></div></div>`}
function bind(){if(started)return;started=true;document.addEventListener('click',async e=>{const el=e.target.closest?.('[data-contact-new],[data-edit-contact],[data-delete-contact],[data-rel],[data-contact-save],[data-modal-close],[data-filter-apply],[data-filter-clear]');if(!el)return;if(el.matches('[data-modal-close]')){el.closest('[data-contactModal]')?.remove();return}if(el.matches('[data-contact-new]')){modal();return}if(el.matches('[data-edit-contact]')){const ovId=el.dataset.editContact;modal(ovId);const b=document.querySelector('[data-contact-save]');if(b)b.dataset.id=ovId;return}if(el.matches('[data-contact-save]')){await saveModal(el.closest('[data-contactModal]'));return}if(el.matches('[data-rel]')){const id=String(el.dataset.rel);expanded=expanded===id?null:id;w.render?.();return}if(el.matches('[data-filter-apply]')){S.contFilters=S.contFilters||{};S.contFilters.nombre=document.querySelector('[data-filter="nombre"]')?.value||'';S.contFilters.empresa=document.querySelector('[data-filter="empresa"]')?.value||'';S.contFilters.cargo=document.querySelector('[data-filter="cargo"]')?.value||'';w.render?.();return}if(el.matches('[data-filter-clear]')){S.contFilters={nombre:'',empresa:'',cargo:''};w.render?.();return}if(el.matches('[data-delete-contact]')){const c=(S.contactos||[]).find(x=>N(x.id)===N(el.dataset.deleteContact));if(!c)return;if(!confirm(c.esCliente?'¿Eliminar este contacto de la agenda? Se conservarán cotizaciones y pagos.':'¿Eliminar este contacto?'))return;S.contactos=S.contactos.filter(x=>N(x.id)!==N(c.id));await w.saveContactos?.(S.user?.uid);w.render?.()}})}
function hideOld(){document.querySelectorAll('#nav button,#nav a,#nav option').forEach(x=>{const t=N(x.textContent||x.value);if(t==='clientes'||t==='clientes y proyectos'){if(x.tagName==='OPTION'){x.textContent='Contactos y clientes';x.value='contactos'}else x.style.display='none'}})}
function run(){if(!w.S)return;hideOld();migrateStoredClients();const changed=ensureQuoteClients();if(S.view==='clientes')S.view='contactos';if(S.view==='contactos'){const m=document.getElementById('main');if(m&&!m.querySelector('[data-contact-new]'))m.innerHTML=view();if(changed&&!saving){persist()}}}
w.viewContactos=view;w.viewClientes=view;w.abrirEditorContactoFusion=modal;
function init(){bind();run();let n=0;const retry=()=>{run();if(++n<20)setTimeout(retry,500)};setTimeout(retry,200);const nav=document.getElementById('nav');if(nav)new MutationObserver(hideOld).observe(nav,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(window);
