// ============================================================
// FINANZAS - Centro financiero + pagos personales/recurrentes
// Este módulo NO envuelve render().
// ============================================================
(function (global) {
    'use strict';

    const STORAGE_KEY='pagosFijos'; let loadedUid=null,loading=false;
    const uid=()=>S.user?.uid||null, mesActual=()=>new Date().toISOString().slice(0,7);
    const escF=v=>typeof esc==='function'?esc(v??''):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
    const dinero=v=>typeof bs==='function'?bs(Number(v)||0):`Bs ${Number(v||0).toFixed(2)}`;
    const nuevoId=()=>global.crypto?.randomUUID?crypto.randomUUID():`pf_${Date.now()}_${Math.random().toString(36).slice(2)}`;

    async function loadPagosFijos(force=false){const userId=uid();if(!userId)return[];if(!force&&loadedUid===userId&&Array.isArray(S.pagosFijos))return S.pagosFijos;if(loading)return S.pagosFijos||[];loading=true;try{const raw=typeof cloudGet==='function'?await cloudGet(userId,STORAGE_KEY):localStorage.getItem(`${STORAGE_KEY}_${userId}`);const data=typeof raw==='string'?JSON.parse(raw||'[]'):(Array.isArray(raw)?raw:[]);S.pagosFijos=Array.isArray(data)?data:[];loadedUid=userId;}catch(e){console.warn('No se pudieron cargar los pagos fijos:',e);S.pagosFijos=S.pagosFijos||[];}finally{loading=false;}return S.pagosFijos;}
    async function savePagosFijos(){const userId=uid();if(!userId)return false;try{if(typeof saveDataKey==='function')await saveDataKey(userId,STORAGE_KEY,S.pagosFijos);else localStorage.setItem(`${STORAGE_KEY}_${userId}`,JSON.stringify(S.pagosFijos||[]));return true;}catch(e){console.warn('No se pudieron guardar los pagos fijos:',e);return false;}}
    function normalizarPago(p){return{id:p.id||nuevoId(),nombre:p.nombre||'Pago',categoria:p.categoria||'Hogar',monto:Number(p.monto)||0,dia:Number(p.dia)||1,pagadoMes:p.pagadoMes||'',fechaPago:p.fechaPago||'',notas:p.notas||''};}
    function estaPagado(p){return p.pagadoMes===mesActual();}
    async function togglePagoFijo(id){await loadPagosFijos();const p=S.pagosFijos.find(x=>String(x.id)===String(id));if(!p)return;if(estaPagado(p)){p.pagadoMes='';p.fechaPago='';}else{p.pagadoMes=mesActual();p.fechaPago=new Date().toISOString().slice(0,10);}await savePagosFijos();render();}
    async function agregarPagoFijo(){const nombre=prompt('¿Qué pago quieres controlar?\nEj.: Internet, Luz, Escuela');if(!nombre?.trim())return;const categoria=prompt('Categoría (Hogar, Educación, Servicios, etc.)','Hogar')||'General';const monto=Number(prompt('Monto aproximado en Bs','0'))||0;const dia=Math.min(31,Math.max(1,Number(prompt('Día habitual de pago (1-31)','5'))||1));await loadPagosFijos();S.pagosFijos.push(normalizarPago({nombre:nombre.trim(),categoria:categoria.trim(),monto,dia}));await savePagosFijos();render();}
    async function editarPagoFijo(id){await loadPagosFijos();const p=S.pagosFijos.find(x=>String(x.id)===String(id));if(!p)return;const nombre=prompt('Nombre',p.nombre);if(!nombre?.trim())return;const monto=Number(prompt('Monto aproximado en Bs',p.monto))||0;const dia=Math.min(31,Math.max(1,Number(prompt('Día habitual',p.dia))||1));p.nombre=nombre.trim();p.monto=monto;p.dia=dia;await savePagosFijos();render();}
    async function eliminarPagoFijo(id){await loadPagosFijos();const p=S.pagosFijos.find(x=>String(x.id)===String(id));if(!p||!confirm(`¿Eliminar el control de "${p.nombre}"?`))return;S.pagosFijos=S.pagosFijos.filter(x=>String(x.id)!==String(id));await savePagosFijos();render();}

    function buildPagosFijos(){const rows=(S.pagosFijos||[]).slice().sort((a,b)=>Number(a.dia||99)-Number(b.dia||99)),pendientes=rows.filter(p=>!estaPagado(p)).length,total=rows.reduce((s,p)=>s+Number(p.monto||0),0);return `<div class="panel" id="pagos-fijos-panel" style="margin-top:18px;"><div class="panel-h"><div><h3>🧾 Pagos por hacer</h3><span>${pendientes} pendientes este mes · ${dinero(total)} estimados</span></div><button class="btn btn-sm btn-primary" onclick="agregarPagoFijo()">+ Agregar pago</button></div><div class="panel-body">${rows.length?`<div style="display:grid;gap:8px;">${rows.map(p=>{const pagado=estaPagado(p);return `<div style="display:grid;grid-template-columns:auto minmax(0,1fr) auto auto;gap:12px;align-items:center;padding:11px 4px;border-bottom:1px solid var(--border);"><input type="checkbox" ${pagado?'checked':''} onchange="togglePagoFijo('${escF(p.id)}')" style="width:18px;height:18px;cursor:pointer;"><div style="min-width:0;"><div style="font-weight:550;${pagado?'text-decoration:line-through;opacity:.6;':''}">${escF(p.nombre)}</div><div style="font-size:11px;color:var(--text-soft);">${escF(p.categoria)} · vence aprox. día ${Number(p.dia)||1}${p.fechaPago?` · pagado ${escF(p.fechaPago)}`:''}</div></div><div style="font-size:13px;font-weight:600;white-space:nowrap;${pagado?'opacity:.55;':''}">${dinero(p.monto)}</div><div style="display:flex;gap:4px;"><button class="iconbtn" title="Editar" onclick="editarPagoFijo('${escF(p.id)}')">✎</button><button class="iconbtn" title="Eliminar" onclick="eliminarPagoFijo('${escF(p.id)}')">×</button></div></div>`;}).join('')}</div>`:'<div class="empty" style="padding:22px;">No tienes pagos recurrentes registrados.</div>'}</div></div>`;}

    function getFinancialSummarySafe(){return typeof getResumenPagos==='function'?getResumenPagos():{totalCobrado:0,totalPorCobrar:0,deudasPendientes:0,deudasParciales:0,deudasPagadas:0};}
    function getCartera(){return(S.cotizaciones||[]).map(c=>({...c,...(typeof getResumenCotizacion==='function'?getResumenCotizacion(c):{saldoPendiente:0,montoTotal:0,totalPagado:0,porcentaje:0})})).filter(c=>Number(c.montoTotal)>0&&Number(c.saldoPendiente)>.01).sort((a,b)=>b.saldoPendiente-a.saldoPendiente);}
    function getFilterState(){if(!S.finanzasFilters)S.finanzasFilters={year:'all',month:'all',status:'all'};return S.finanzasFilters;}
    function getFilteredCartera(){const f=getFilterState();let rows=getCartera();if(f.year!=='all'||f.month!=='all'){rows=rows.filter(c=>{const d=String(c.fecha||c.fechaAceptacion||c.createdAt||'').slice(0,7);if(!d)return true;const [y,m]=d.split('-');return(f.year==='all'||y===f.year)&&(f.month==='all'||m===f.month);});}if(f.status==='pendiente')rows=rows.filter(c=>Number(c.totalPagado||0)<=.01);if(f.status==='parcial')rows=rows.filter(c=>Number(c.totalPagado||0)>.01&&Number(c.saldoPendiente||0)>.01);return rows;}
    function yearsAvailable(){const ys=new Set();(S.cotizaciones||[]).forEach(c=>{const d=String(c.fecha||c.fechaAceptacion||c.createdAt||'').slice(0,4);if(/^\d{4}$/.test(d))ys.add(d);});const now=String(new Date().getFullYear());ys.add(now);return Array.from(ys).sort((a,b)=>b.localeCompare(a));}
    function applyFinanceFilters(){const y=document.getElementById('fin-year'),m=document.getElementById('fin-month'),st=document.getElementById('fin-status');const f=getFilterState();f.year=y?.value||'all';f.month=m?.value||'all';f.status=st?.value||'all';render();}
    function clearFinanceFilters(){S.finanzasFilters={year:'all',month:'all',status:'all'};render();}
    function bindFinanceFilters(){['fin-year','fin-month','fin-status'].forEach(id=>{const e=document.getElementById(id);if(e)e.onchange=applyFinanceFilters;});const b=document.getElementById('fin-clear');if(b)b.onclick=clearFinanceFilters;}

    function buildFilterBar(){const f=getFilterState(),ys=yearsAvailable();return `<div class="panel" style="margin-bottom:18px;"><div class="panel-body" style="padding:12px 14px;"><div style="display:flex;gap:10px;align-items:end;flex-wrap:wrap;"><div class="field" style="margin:0;min-width:130px;"><label>Año</label><select id="fin-year"><option value="all">Todos</option>${ys.map(y=>`<option value="${y}" ${f.year===y?'selected':''}>${y}</option>`).join('')}</select></div><div class="field" style="margin:0;min-width:130px;"><label>Mes</label><select id="fin-month"><option value="all">Todos</option>${['01','02','03','04','05','06','07','08','09','10','11','12'].map((m,i)=>`<option value="${m}" ${f.month===m?'selected':''}>${String(i+1).padStart(2,'0')} · ${new Date(2020,i,1).toLocaleDateString('es-BO',{month:'long'})}</option>`).join('')}</select></div><div class="field" style="margin:0;min-width:160px;"><label>Estado</label><select id="fin-status"><option value="all" ${f.status==='all'?'selected':''}>Todos</option><option value="pendiente" ${f.status==='pendiente'?'selected':''}>Pendiente</option><option value="parcial" ${f.status==='parcial'?'selected':''}>Pago parcial</option></select></div><button class="btn btn-sm btn-ghost" id="fin-clear">Limpiar filtros</button></div></div></div>`;}

    function viewFinanzas(){const r=getFinancialSummarySafe(),f=getFilterState(),cots=getFilteredCartera(),total= cots.reduce((s,c)=>s+Number(c.montoTotal||0),0),cobrado=cots.reduce((s,c)=>s+Number(c.totalPagado||0),0),saldo=cots.reduce((s,c)=>s+Number(c.saldoPendiente||0),0);return `<div class="page-head"><div><h1>💰 Finanzas</h1><p>Control de cobros profesionales y pagos personales</p></div><button class="btn btn-ghost" onclick="S.view='dashboard';render();">← Dashboard</button></div>${buildFilterBar()}<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px;margin-bottom:18px;">${[['💵','Cobrado',r.totalCobrado],['📥','Por cobrar',r.totalPorCobrar],['⏳','Pendientes',r.deudasPendientes],['🔄','Parciales',r.deudasParciales],['✅','Completados',r.deudasPagadas]].map(x=>`<div class="panel" style="padding:15px;margin:0;"><div style="font-size:11px;color:var(--text-soft);">${x[0]} ${x[1]}</div><div style="font-size:20px;font-weight:650;margin-top:5px;">${['Pendientes','Parciales','Completados'].includes(x[1])?x[2]:dinero(x[2])}</div></div>`).join('')}</div>${(f.year!=='all'||f.month!=='all'||f.status!=='all')?`<div style="font-size:12px;color:var(--text-soft);margin:-8px 0 14px;">Filtro aplicado: ${f.year==='all'?'todos los años':f.year}${f.month!=='all'?` · mes ${f.month}`:''}${f.status!=='all'?` · ${f.status}`:''} · ${cots.length} registros · Total ${dinero(total)} · Cobrado ${dinero(cobrado)} · Saldo ${dinero(saldo)}</div>`:''}${buildPagosFijos()}<div class="panel" style="margin-top:18px;"><div class="panel-h"><div><h3>📌 Cartera por cobrar</h3><span>${cots.length} registro${cots.length===1?'':'s'} · Ordenada por mayor saldo</span></div></div><div class="panel-body">${cots.length?`<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Proyecto</th><th>Total</th><th>Cobrado</th><th>Saldo</th><th>Avance</th></tr></thead><tbody>${cots.map(c=>`<tr><td>${escF(c.cliente||'')}</td><td>${escF(c.titulo||c.proyecto||'')}</td><td class="tright tnum">${dinero(c.montoTotal)}</td><td class="tright tnum">${dinero(c.totalPagado)}</td><td class="tright tnum"><strong>${dinero(c.saldoPendiente)}</strong></td><td>${Number(c.porcentaje||0).toFixed(0)}%</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty" style="padding:20px;">No hay deudas que coincidan con los filtros.</div>'}</div></div>`;}

    async function ensureData(){if(uid())await loadPagosFijos();}
    async function syncPagosFijosDashboard(){if(S.view!=='dashboard')return;await ensureData();if(S.view!=='dashboard')return;const main=document.getElementById('main');if(!main)return;const old=document.getElementById('pagos-fijos-panel');if(old)old.outerHTML=buildPagosFijos();else{const panels=main.querySelectorAll('.panel');const target=panels[panels.length-1];if(target)target.insertAdjacentHTML('afterend',buildPagosFijos());}}
    global.togglePagoFijo=togglePagoFijo;global.agregarPagoFijo=agregarPagoFijo;global.editarPagoFijo=editarPagoFijo;global.eliminarPagoFijo=eliminarPagoFijo;global.viewFinanzas=viewFinanzas;global.syncPagosFijosDashboard=syncPagosFijosDashboard;global.applyFinanceFilters=applyFinanceFilters;
    // La vista financiera es síncrona; los filtros se enlazan después de pintar.
    const originalViewFinanzas=global.viewFinanzas;
    global.viewFinanzas=function(){const html=originalViewFinanzas();setTimeout(bindFinanceFilters,0);return html;};
})(window);
